name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: '[BUG]: '
labels: ['bug', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have checked the documentation
          required: true
        - label: This issue contains no sensitive information (API keys, passwords, etc.)
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System down, data loss, security vulnerability)
        - High (Major functionality broken)
        - Medium (Feature partially working)
        - Low (Minor issue, workaround available)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Authentication
        - Dashboard
        - API
        - Database
        - UI/Frontend
        - Backend
        - CI/CD
        - Documentation
        - Security
        - Compliance
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      placeholder: |
        - OS: [e.g. Windows 11, macOS 13, Ubuntu 22.04]
        - Browser: [e.g. Chrome 120, Firefox 121, Safari 17]
        - Node.js version: [e.g. 20.10.0]
        - Application version: [e.g. 1.2.3]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant log output
      render: shell
      placeholder: Paste error logs here...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here...

  - type: checkboxes
    id: security
    attributes:
      label: Security Impact
      description: Does this bug have security implications?
      options:
        - label: This bug could have security implications
        - label: This bug involves sensitive data
        - label: This bug affects authentication/authorization
        - label: This bug affects data encryption

  - type: checkboxes
    id: compliance
    attributes:
      label: Compliance Impact
      description: Does this bug affect compliance?
      options:
        - label: This bug affects GDPR compliance
        - label: This bug affects SOC 2 controls
        - label: This bug affects audit trails
        - label: This bug affects data retention

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...
