name: 🔒 Security Issue
description: Report a security vulnerability or concern (Use responsibly)
title: '[SECURITY]: '
labels: ['security', 'critical', 'needs-immediate-attention']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT SECURITY NOTICE** ⚠️

        If you believe you have found a **critical security vulnerability**, please:
        1. **DO NOT** create a public issue
        2. Contact our security team directly at: security@synapses.com
        3. Use our responsible disclosure process

        This template is for **non-critical security concerns** and **security enhancement requests** only.

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Security Acknowledgment
      description: Please confirm your understanding
      options:
        - label: I understand this is for non-critical security issues only
          required: true
        - label: I have not included sensitive information in this report
          required: true
        - label: I will follow responsible disclosure practices
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Security Severity
      description: How would you classify this security concern?
      options:
        - Low (Security enhancement, best practice)
        - Medium (Potential security weakness)
        - High (Should be reported privately)
        - Critical (MUST be reported privately)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Authentication
        - Authorization
        - Data Protection
        - Input Validation
        - Encryption
        - Session Management
        - API Security
        - Infrastructure
        - Dependency Vulnerability
        - Configuration
        - Compliance
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Concern Description
      description: Describe the security concern (avoid sensitive details)
      placeholder: |
        Provide a general description of the security concern without revealing:
        - Specific exploit details
        - Actual vulnerable code
        - Step-by-step attack vectors
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could be the potential impact if this issue is exploited?
      placeholder: |
        Describe the potential impact in general terms:
        - Data exposure risk
        - System availability
        - User privacy
        - Compliance implications
    validations:
      required: true

  - type: textarea
    id: affected_components
    attributes:
      label: Affected Components
      description: Which parts of the system are affected?
      placeholder: |
        List affected components:
        - Frontend/UI
        - Backend API
        - Database
        - Authentication system
        - Third-party integrations
        - Infrastructure

  - type: checkboxes
    id: compliance_impact
    attributes:
      label: Compliance Impact
      description: Could this affect compliance requirements?
      options:
        - label: May affect GDPR compliance
        - label: May affect SOC 2 controls
        - label: May affect data retention policies
        - label: May affect audit requirements
        - label: May affect industry-specific regulations

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: In which environment was this observed?
      placeholder: |
        - Environment: [Development/Staging/Production]
        - Browser: [if applicable]
        - Version: [if known]
        - Configuration: [relevant details]

  - type: textarea
    id: recommendations
    attributes:
      label: Recommended Actions
      description: What actions do you recommend to address this concern?
      placeholder: |
        Suggest general recommendations:
        - Security controls to implement
        - Best practices to follow
        - Configuration changes
        - Code review areas

  - type: checkboxes
    id: urgency
    attributes:
      label: Urgency Assessment
      description: How urgent is this security concern?
      options:
        - label: Immediate attention required
        - label: Should be addressed in next sprint
        - label: Can be planned for future release
        - label: Enhancement for consideration

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant security standards, guidelines, or documentation
      placeholder: |
        - OWASP guidelines
        - Security standards (ISO 27001, NIST, etc.)
        - Industry best practices
        - Relevant CVE numbers
        - Documentation links

  - type: markdown
    attributes:
      value: |
        ---

        **Remember:**
        - For critical vulnerabilities, use our private security contact
        - Follow responsible disclosure practices
        - Do not include sensitive information in public issues
        - Security team will respond within 24 hours for critical issues

        **Security Contact:** security@synapses.com
