name: Promptfoo Test

on:
  push:
    paths:
      - 'prompt-tests/**'
      - '.github/workflows/promptfoo-ci.yml'
  pull_request:
    paths:
      - 'prompt-tests/**'
      - '.github/workflows/promptfoo-ci.yml'

jobs:
  promptfoo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install promptfoo CLI
        run: npm install -g promptfoo
      - name: Run promptfoo tests
        run: promptfoo test prompt-tests/*.yml